export const BOOK_ADD_REQUEST = 'BOOK_ADD_REQUEST'
export const BOOK_ADD_SUCCESS = 'BOOK_ADD_SUCCESS'
export const BOOK_ADD_FAIL = 'BOOK_ADD_FAIL'

export const BOOK_COVER_UPLOAD_REQUEST = 'BOOK_COVER_UPLOAD_REQUEST'
export const BOOK_COVER_UPLOAD_SUCCESS = 'BOOK_COVER_UPLOAD_SUCCESS'
export const BOOK_COVER_UPLOAD_FAIL = 'BOOK_COVER_UPLOAD_FAIL'

export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST'
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS'
export const GET_BOOKS_FAIL = 'GET_BOOKS_FAIL'

export const GET_BOOKS_BY_TITLE_STRING_REQUEST =
  'GET_BOOKS_BY_TITLE_STRING_REQUEST'
export const GET_BOOKS_BY_TITLE_STRING_SUCCESS =
  'GET_BOOKS_BY_TITLE_STRING_SUCCESS'
export const GET_BOOKS_BY_TITLE_STRING_FAIL = 'GET_BOOKS_BY_TITLE_STRING_FAIL'

export const GET_BOOKS_BY_LIBRARY_REQUEST = 'GET_BOOKS_BY_LIBRARY_REQUEST'
export const GET_BOOKS_BY_LIBRARY_SUCCESS = 'GET_BOOKS_BY_LIBRARY_SUCCESS'
export const GET_BOOKS_BY_LIBRARY_FAIL = 'GET_BOOKS_BY_LIBRARY_FAIL'
