export const CHECK_OUT_BOOK_BY_LIBRARIAN_REQUEST =
  'CHECK_OUT_BOOK_BY_LIBRARIAN_REQUEST'
export const CHECK_OUT_BOOK_BY_LIBRARIAN_SUCCESS =
  'CHECK_OUT_BOOK_BY_LIBRARIAN_SUCCESS'
export const CHECK_OUT_BOOK_BY_LIBRARIAN_FAIL =
  'CHECK_OUT_BOOK_BY_LIBRARIAN_FAIL'
