export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const USER_ACTIVATION_REQUEST = 'USER_ACTIVATION_REQUEST'
export const USER_ACTIVATION_SUCCESS = 'USER_ACTIVATION_SUCCESS'
export const USER_ACTIVATION_FAIL = 'USER_ACTIVATION_FAIL'

export const USER_IMAGE_REQUEST = 'USER_IMAGE_REQUEST'
export const USER_IMAGE_SUCCESS = 'USER_IMAGE_SUCCESS'
export const USER_IMAGE_FAIL = 'USER_IMAGE_FAIL'
