export const RETURN_BOOK_BY_LIBRARIAN_REQUEST =
  'RETURN_BOOK_BY_LIBRARIAN_REQUEST'
export const RETURN_BOOK_BY_LIBRARIAN_SUCCESS =
  'RETURN_BOOK_BY_LIBRARIAN_SUCCESS'
export const RETURN_BOOK_BY_LIBRARIAN_FAIL = 'RETURN_BOOK_BY_LIBRARIAN_FAIL'

export const SEND_DUE_NOTIFICATIONS_TO_USER_REQUEST =
  'SEND_DUE_NOTIFICATIONS_TO_USER_REQUEST'
export const SEND_DUE_NOTIFICATIONS_TO_USER_SUCCESS =
  'SEND_DUE_NOTIFICATIONS_TO_USER_SUCCESS'
export const SEND_DUE_NOTIFICATIONS_TO_USER_FAIL =
  'SEND_DUE_NOTIFICATIONS_TO_USER_FAIL'
