export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL'

export const USER_PROFILE_PIC_REQUEST = 'USER_PROFILE_PIC_REQUEST'
export const USER_PROFILE_PIC_SUCCESS = 'USER_PROFILE_PIC_SUCCESS'
export const USER_PROFILE_PIC_FAIL = 'USER_PROFILE_PIC_FAIL'

export const USER_PROFILE_PIC_UPLOAD_REQUEST = 'USER_PROFILE_PIC_UPLOAD_REQUEST'
export const USER_PROFILE_PIC_UPLOAD_SUCCESS = 'USER_PROFILE_PIC_UPLOAD_SUCCESS'
export const USER_PROFILE_PIC_UPLOAD_FAIL = 'USER_PROFILE_PIC_UPLOAD_FAIL'

export const USER_EMAIL_OTP_REQUEST = 'USER_EMAIL_OTP_REQUEST'
export const USER_EMAIL_OTP_SUCCESS = 'USER_EMAIL_OTP_SUCCESS'
export const USER_EMAIL_OTP_FAIL = 'USER_EMAIL_OTP_FAIL'

export const USER_PASS_RESET_REQUEST = 'USER_PASS_RESET_REQUEST'
export const USER_PASS_RESET_SUCCESS = 'USER_PASS_RESET_SUCCESS'
export const USER_PASS_RESET_FAIL = 'USER_PASS_RESET_FAIL'
