export const GET_BOOKS_BY_LIBRARY_REQUEST = 'GET_BOOKS_BY_LIBRARY_REQUEST'
export const GET_BOOKS_BY_LIBRARY_SUCCESS = 'GET_BOOKS_BY_LIBRARY_SUCCESS'
export const GET_BOOKS_BY_LIBRARY_FAIL = 'GET_BOOKS_BY_LIBRARY_FAIL'

export const GET_BOOKS_BY_TITLE_STRING_REQUEST =
  'GET_BOOKS_BY_TITLE_STRING_REQUEST'
export const GET_BOOKS_BY_TITLE_STRING_SUCCESS =
  'GET_BOOKS_BY_TITLE_STRING_SUCCESS'
export const GET_BOOKS_BY_TITLE_STRING_FAIL = 'GET_BOOKS_BY_TITLE_STRING_FAIL'
