export const DELETE_USER_CHECKOUTBOOK_REQUEST =
  'DELETE_USER_CHECKOUTBOOK_REQUEST'
export const DELETE_USER_CHECKOUTBOOK_SUCCESS =
  'DELETE_USER_CHECKOUTBOOK_SUCCESS'
export const DELETE_USER_CHECKOUTBOOK_FAIL = 'DELETE_USER_CHECKOUTBOOK_FAIL'

export const ISSUE_USER_CHECKOUTBOOK_REQUEST = 'ISSUE_USER_CHECKOUTBOOK_REQUEST'
export const ISSUE_USER_CHECKOUTBOOK_SUCCESS = 'ISSUE_USER_CHECKOUTBOOK_SUCCESS'
export const ISSUE_USER_CHECKOUTBOOK_FAIL = 'ISSUE_USER_CHECKOUTBOOK_FAIL'
