export const USER_RESERVATION_ADD_REQUEST = 'USER_RESERVATION_ADD_REQUEST'
export const USER_RESERVATION_ADD_SUCCESS = 'USER_RESERVATION_ADD_SUCCESS'
export const USER_RESERVATION_ADD_FAIL = 'USER_RESERVATION_ADD_FAIL'

export const FETCH_USER_RESERVATIONS_REQUEST = 'FETCH_USER_RESERVATIONS_REQUEST'
export const FETCH_USER_RESERVATIONS_SUCCESS = 'FETCH_USER_RESERVATIONS_SUCCESS'
export const FETCH_USER_RESERVATIONS_FAIL = 'FETCH_USER_RESERVATIONS_FAIL'

export const DELETE_USER_RESERVATION_REQUEST = 'DELETE_USER_RESERVATION_REQUEST'
export const DELETE_USER_RESERVATION_SUCCESS = 'DELETE_USER_RESERVATION_SUCCESS'
export const DELETE_USER_RESERVATION_FAIL = 'DELETE_USER_RESERVATION_FAIL'
