export const FETCH_USER_RESERVATION_HISTORIES_REQUEST =
  'FETCH_USER_RESERVATION_HISTORIES_REQUEST'
export const FETCH_USER_RESERVATION_HISTORIES_SUCCESS =
  'FETCH_USER_RESERVATION_HISTORIES_SUCCESS'
export const FETCH_USER_RESERVATION_HISTORIES_FAIL =
  'FETCH_USER_RESERVATION_HISTORIES_FAIL'
