export const ISSUE_USER_RETURNBOOK_REQUEST = 'ISSUE_USER_RETURNBOOK_REQUEST'
export const ISSUE_USER_RETURNBOOK_SUCCESS = 'ISSUE_USER_RETURNBOOK_SUCCESS'
export const ISSUE_USER_RETURNBOOK_FAIL = 'ISSUE_USER_RETURNBOOK_FAIL'

export const CALCULATE_FINE_OF_USER_REQUEST = 'CALCULATE_FINE_OF_USER_REQUEST'
export const CALCULATE_FINE_OF_USER_SUCCESS = 'CALCULATE_FINE_OF_USER_SUCCESS'
export const CALCULATE_FINE_OF_USER_FAIL = 'CALCULATE_FINE_OF_USER_FAIL'

export const PAY_FINE_OF_USER_REQUEST = 'PAY_FINE_OF_USER_REQUEST'
export const PAY_FINE_OF_USER_SUCCESS = 'PAY_FINE_OF_USER_SUCCESS'
export const PAY_FINE_OF_USER_FAIL = 'PAY_FINE_OF_USER_FAIL'
